export const SERVER_CONFIG_REFERENCE = [
  {
    section: 'Runtime',
    path: 'log_stats_enabled',
    label: 'Enable -logStats',
    type: 'startup flag',
    defaultValue: 'Enabled by this dashboard',
    description: 'Adds periodic performance lines to the server log so the dashboard can derive FPS and richer health signals.',
    notes: 'Provision new servers with this enabled unless you have a specific reason to suppress telemetry.',
  },
  {
    section: 'Runtime',
    path: 'max_fps',
    label: 'Max FPS',
    type: 'number',
    defaultValue: '120',
    description: 'Caps dedicated-server simulation FPS to save host performance.',
    notes: 'Bohemia highlights limiting max FPS as an important public-hosting optimization.',
  },
  {
    section: 'Runtime',
    path: 'startup_parameters',
    label: 'Extra Startup Parameters',
    type: 'string list',
    defaultValue: '[]',
    description: 'Additional engine startup flags appended at launch time.',
    notes: 'Use for advanced runtime switches that are not part of the JSON config.',
  },
  {
    section: 'Game',
    path: 'game.name',
    label: 'Server Name',
    type: 'string',
    defaultValue: 'Server name',
    description: 'Display name shown in the browser and Steam query responses.',
  },
  {
    section: 'Game',
    path: 'game.password',
    label: 'Join Password',
    type: 'string',
    defaultValue: 'empty',
    description: 'Password required for players to join the server.',
  },
  {
    section: 'Game',
    path: 'game.passwordAdmin',
    label: 'Admin Password',
    type: 'string',
    defaultValue: 'empty',
    description: 'Password used with #login for in-game admin control.',
    notes: 'The admin password must not contain spaces.',
  },
  {
    section: 'Game',
    path: 'game.admins',
    label: 'Listed Admins',
    type: 'identity list',
    defaultValue: '[]',
    description: 'IdentityIds or SteamIds treated as server admins regardless of current login state.',
    notes: 'IdentityIds get priority queue behavior when join queue is enabled.',
  },
  {
    section: 'Game',
    path: 'game.scenarioId',
    label: 'Scenario ID',
    type: 'resource path',
    defaultValue: '{ECC61978EDCC2B5A}Missions/23_Campaign.conf',
    description: 'Mission .conf path to boot when the server starts.',
    notes: 'Reforger currently supports one active scenario, not mission rotation.',
  },
  {
    section: 'Game',
    path: 'game.maxPlayers',
    label: 'Max Players',
    type: 'number',
    defaultValue: '64',
    description: 'Maximum concurrent player slots.',
  },
  {
    section: 'Game',
    path: 'game.visible',
    label: 'Visible',
    type: 'boolean',
    defaultValue: 'true',
    description: 'Controls whether the server appears in the browser.',
  },
  {
    section: 'Game',
    path: 'game.crossPlatform',
    label: 'Cross Platform',
    type: 'boolean',
    defaultValue: 'true',
    description: 'Allows all supported platforms when enabled.',
    notes: 'The dashboard/backend default is true, although Bohemia documentation may describe a false engine-doc default. Bohemia recommends using this switch instead of hand-editing platform lists in most cases.',
  },
  {
    section: 'Game',
    path: 'game.supportedPlatforms',
    label: 'Supported Platforms',
    type: 'enum list',
    defaultValue: '["PC","XBL","PSN"]',
    description: 'Explicit platform allow-list for PC, Xbox, and PlayStation clients.',
  },
  {
    section: 'Game',
    path: 'game.modsRequiredByDefault',
    label: 'Mods Required By Default',
    type: 'boolean',
    defaultValue: 'true',
    description: 'Sets the default required flag for entries in the mods array.',
  },
  {
    section: 'Game',
    path: 'game.mods[].required',
    label: 'Per-Mod Required',
    type: 'boolean',
    defaultValue: 'inherits modsRequiredByDefault',
    description: 'Marks a mod as optional or required for clients and server startup.',
    notes: 'Optional mods can be removed with a warning if they fail to download.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.serverMaxViewDistance',
    label: 'Server Max View Distance',
    type: 'number',
    defaultValue: '1600',
    description: 'Upper view-distance clamp applied to clients.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.serverMinGrassDistance',
    label: 'Server Min Grass Distance',
    type: 'number',
    defaultValue: '0',
    description: 'Minimum grass distance forced on clients. Zero disables the override.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.networkViewDistance',
    label: 'Network View Distance',
    type: 'number',
    defaultValue: '1500',
    description: 'Maximum network streaming range for replicated entities.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.fastValidation',
    label: 'Fast Validation',
    type: 'boolean',
    defaultValue: 'true',
    description: 'Validates client state on join using the minimal public-server-safe data path.',
    notes: 'Bohemia explicitly recommends keeping this true for public servers.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.battlEye',
    label: 'BattlEye',
    type: 'boolean',
    defaultValue: 'true',
    description: 'Enables or disables BattlEye.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.disableThirdPerson',
    label: 'Disable Third Person',
    type: 'boolean',
    defaultValue: 'false',
    description: 'Forces clients into first-person only.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.VONDisableUI',
    label: 'Disable VON UI',
    type: 'boolean',
    defaultValue: 'false',
    description: 'Hides the VON user interface from clients.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.VONDisableDirectSpeechUI',
    label: 'Disable Direct Speech UI',
    type: 'boolean',
    defaultValue: 'false',
    description: 'Hides the direct-speech VON interface from clients.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.VONCanTransmitCrossFaction',
    label: 'Cross-Faction Radio Transmit',
    type: 'boolean',
    defaultValue: 'false',
    description: 'Lets players transmit on radios belonging to other factions.',
  },
  {
    section: 'Gameplay',
    path: 'game.gameProperties.missionHeader',
    label: 'Mission Header Override',
    type: 'JSON object',
    defaultValue: '{}',
    description: 'Overrides scenario metadata such as name, description, start time, weather, and conflict-specific campaign tuning.',
  },
  {
    section: 'Persistence',
    path: 'game.persistence.autoSaveInterval',
    label: 'Auto Save Interval',
    type: 'number',
    defaultValue: '10',
    description: 'Minutes between automatic persistence saves. Zero disables autosave.',
  },
  {
    section: 'Persistence',
    path: 'game.persistence.hiveId',
    label: 'Hive ID',
    type: 'number',
    defaultValue: '0',
    description: 'Separates save-game UUID space when multiple servers share the same persistence database.',
  },
  {
    section: 'Persistence',
    path: 'game.persistence.databases',
    label: 'Database Overrides',
    type: 'JSON object',
    defaultValue: '{}',
    description: 'Named persistence database definitions or overrides, including preset and per-database options.',
  },
  {
    section: 'Persistence',
    path: 'game.persistence.storages',
    label: 'Storage Overrides',
    type: 'JSON object',
    defaultValue: '{}',
    description: 'Named storage overrides that can point persistence storage at specific configured databases.',
  },
  {
    section: 'RCON',
    path: 'rcon.password',
    label: 'RCON Password',
    type: 'string',
    defaultValue: 'generated',
    description: 'Required for BattlEye RCON to start.',
    notes: 'Must be at least three characters and cannot contain spaces.',
  },
  {
    section: 'RCON',
    path: 'rcon.permission',
    label: 'RCON Permission',
    type: 'enum',
    defaultValue: 'admin',
    description: 'Default permission granted to connecting RCON clients.',
    notes: 'Allowed values are admin and monitor.',
  },
  {
    section: 'RCON',
    path: 'rcon.maxClients',
    label: 'RCON Max Clients',
    type: 'number',
    defaultValue: '16',
    description: 'Maximum simultaneous RCON clients.',
  },
  {
    section: 'RCON',
    path: 'rcon.blacklist',
    label: 'RCON Blacklist',
    type: 'string list',
    defaultValue: '[]',
    description: 'Commands explicitly blocked from execution.',
  },
  {
    section: 'RCON',
    path: 'rcon.whitelist',
    label: 'RCON Whitelist',
    type: 'string list',
    defaultValue: '[]',
    description: 'If present, only listed commands may be executed.',
  },
  {
    section: 'Operating',
    path: 'operating.lobbyPlayerSynchronise',
    label: 'Lobby Player Synchronise',
    type: 'boolean',
    defaultValue: 'true',
    description: 'Keeps GameAPI player counts aligned with who is actually present on the server.',
  },
  {
    section: 'Operating',
    path: 'operating.disableCrashReporter',
    label: 'Disable Crash Reporter',
    type: 'boolean',
    defaultValue: 'false',
    description: 'Disables automatic server-side crash reporting.',
  },
  {
    section: 'Operating',
    path: 'operating.disableNavmeshStreaming',
    label: 'Disable Navmesh Streaming',
    type: 'array',
    defaultValue: 'undefined',
    description: 'Loads full navmesh data into memory for selected projects, trading memory for AI responsiveness.',
    notes: 'Empty array disables streaming for all navmeshes.',
  },
  {
    section: 'Operating',
    path: 'operating.disableServerShutdown',
    label: 'Disable Server Shutdown',
    type: 'boolean',
    defaultValue: 'false',
    description: 'Prevents automatic shutdown after backend connection loss.',
  },
  {
    section: 'Operating',
    path: 'operating.disableAI',
    label: 'Disable AI',
    type: 'boolean',
    defaultValue: 'false',
    description: 'Stops AIWorld initialization and ticking completely.',
  },
  {
    section: 'Operating',
    path: 'operating.playerSaveTime',
    label: 'Player Save Time',
    type: 'number',
    defaultValue: '120',
    description: 'Seconds between player save operations for online and local storage.',
  },
  {
    section: 'Operating',
    path: 'operating.aiLimit',
    label: 'AI Limit',
    type: 'number',
    defaultValue: '-1',
    description: 'Hard AI spawn ceiling. Negative values leave the limit disabled.',
  },
  {
    section: 'Operating',
    path: 'operating.slotReservationTimeout',
    label: 'Slot Reservation Timeout',
    type: 'number',
    defaultValue: '60',
    description: 'Seconds a kicked player keeps a reserved slot before timing out.',
  },
  {
    section: 'Operating',
    path: 'operating.joinQueue.maxSize',
    label: 'Join Queue Size',
    type: 'number',
    defaultValue: '0',
    description: 'Maximum number of players allowed in the join queue. Zero disables the queue.',
  },
  {
    section: 'Backend Managed',
    path: 'bindAddress / bindPort / publicAddress / publicPort / a2s.port / rcon.port',
    label: 'Network Bindings',
    type: 'read only',
    defaultValue: 'auto-managed',
    description: 'Host IPs and ports are provisioner-owned so users cannot break Docker networking or port allocation.',
  },
];
